### ISSUE TITLE
Simply brilliant!

### ISSUE THREAD

**Issue by StefanCohen** [ChrisHaPunkt/stihl-imow-webapi#1]
I was just about to try to write a python wrapper for the imow web api as I couldn't find anything when I looked around yesterday. And today I found your repo created just hours ago :) This does exactly what I need and will allow me to dump the stats into InfluxDB for analysis and visualization. Thanks!

Oh. I tried every method exposed and it seems like everything works great with the data from my 522c.

**Comment by ChrisHaPunkt** [comment]
happy to help ;-)

**Comment by lausser** [comment]
Same here. My sister got her 422 PC last week (i urged her to buy a model with internet connectivity and paid her the price difference, because i wanted a toy to play with) and the app shows the mover as "offline" most of the time. I opened a ticket with Stihl and they asked me for internal settings and versions. Although i don't live in her town, thanks to your module i could dump all the required informations from remote. :-)
